import type { Metadata } from 'next';
import '../global.css';
import Header from 'components/header';
import Providers from 'components/Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-Background m-auto h-full w-full min-w-[1152px] max-w-[1152px]`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
