import type { Metadata } from 'next';
import '../global.css';
import Header from 'components/header';
import Providers from 'components/Provider';
import Footer from '@repo/ui/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background-gray-10 h-full w-full`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
      <Footer />
    </html>
  );
}
