export const userListDummy = [
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    username: 'silverbeen',
    sns: 'kakao',
    createdAt: 'YYYY-MM-DD HH:mm:SS',
    status: true,
  },
];

export const movieReportListDummy = [
  {
    id: '1',
    email: 'kub9722@mgila.com',
    reason: '그냥',
    reportedAt: 'YYYY-MM-DD HH:mm:SS',
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    reason: '그냥',
    reportedAt: 'YYYY-MM-DD HH:mm:SS',
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    reason: '그냥',
    reportedAt: 'YYYY-MM-DD HH:mm:SS',
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    reason: '그냥',
    reportedAt: 'YYYY-MM-DD HH:mm:SS',
  },
  {
    id: '1',
    email: 'kub9722@mgila.com',
    reason: '그냥',
    reportedAt: 'YYYY-MM-DD HH:mm:SS',
  },
];
